"""baseline

Revision ID: 2540d625d0fe
Revises:
Create Date: 2026-05-05 14:09:13.600670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2540d625d0fe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thrive_user_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("role", sa.Enum("ADMIN", "DOCTOR", "NURSE", "PATIENT", name="roletypeenum"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_name"),
    )
    op.create_table(
        "thrive_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_role_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=320), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("okta_sub", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=320, collation="NOCASE"), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("show_sql", sa.Boolean(), nullable=True),
        sa.Column("show_table", sa.Boolean(), nullable=True),
        sa.Column("show_plotly_code", sa.Boolean(), nullable=True),
        sa.Column("show_chart", sa.Boolean(), nullable=True),
        sa.Column("show_question_history", sa.Boolean(), nullable=True),
        sa.Column("show_summary", sa.Boolean(), nullable=True),
        sa.Column("voice_input", sa.Boolean(), nullable=True),
        sa.Column("speak_summary", sa.Boolean(), nullable=True),
        sa.Column("show_suggested", sa.Boolean(), nullable=True),
        sa.Column("show_followup", sa.Boolean(), nullable=True),
        sa.Column("show_elapsed_time", sa.Boolean(), nullable=True),
        sa.Column("llm_fallback", sa.Boolean(), nullable=True),
        sa.Column("confirm_magic_commands", sa.Boolean(), nullable=True),
        sa.Column("min_message_id", sa.Integer(), nullable=True),
        sa.Column("theme", sa.String(length=50), nullable=True),
        sa.Column("selected_llm_provider", sa.String(length=50), nullable=True),
        sa.Column("selected_llm_model", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_role_id"],
            ["thrive_user_role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("okta_sub"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "thrive_admin_action",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("target_username", sa.String(length=50), nullable=True),
        sa.Column("target_entity_type", sa.String(length=50), nullable=True),
        sa.Column("target_entity_id", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("old_value", sa.String(), nullable=True),
        sa.Column("new_value", sa.String(), nullable=True),
        sa.Column("affected_count", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["thrive_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["thrive_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("thrive_admin_action", schema=None) as batch_op:
        batch_op.create_index("ix_thrive_admin_action_action_type", ["action_type"], unique=False)
        batch_op.create_index("ix_thrive_admin_action_admin_id", ["admin_id"], unique=False)
        batch_op.create_index("ix_thrive_admin_action_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_thrive_admin_action_target_user_id", ["target_user_id"], unique=False)

    op.create_table(
        "thrive_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.String(length=50), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("feedback", sa.String(length=50), nullable=True),
        sa.Column("feedback_comment", sa.String(length=500), nullable=True),
        sa.Column("training_status", sa.String(length=20), nullable=True),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("question", sa.String(length=1000), nullable=True),
        sa.Column("dataframe", sa.String(), nullable=True),
        sa.Column("elapsed_time", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["thrive_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["thrive_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("thrive_message", schema=None) as batch_op:
        batch_op.create_index("ix_thrive_message_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_thrive_message_feedback", ["feedback"], unique=False)
        batch_op.create_index("ix_thrive_message_training_status", ["training_status"], unique=False)
        batch_op.create_index("ix_thrive_message_type", ["type"], unique=False)
        batch_op.create_index("ix_thrive_message_user_id", ["user_id"], unique=False)

    op.create_table(
        "thrive_user_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("activity_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("old_value", sa.String(), nullable=True),
        sa.Column("new_value", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["thrive_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("thrive_user_activity", schema=None) as batch_op:
        batch_op.create_index("ix_thrive_user_activity_activity_type", ["activity_type"], unique=False)
        batch_op.create_index("ix_thrive_user_activity_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_thrive_user_activity_user_id", ["user_id"], unique=False)

    op.create_table(
        "thrive_error_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("stack_trace", sa.String(), nullable=True),
        sa.Column("question", sa.String(length=1000), nullable=True),
        sa.Column("generated_sql", sa.String(), nullable=True),
        sa.Column("llm_provider", sa.String(length=50), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column("context_data", sa.String(), nullable=True),
        sa.Column("auto_retry_attempted", sa.Boolean(), nullable=True),
        sa.Column("retry_successful", sa.Boolean(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["thrive_message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["thrive_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("thrive_error_log", schema=None) as batch_op:
        batch_op.create_index("ix_thrive_error_log_category", ["category"], unique=False)
        batch_op.create_index("ix_thrive_error_log_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_thrive_error_log_message_id", ["message_id"], unique=False)
        batch_op.create_index("ix_thrive_error_log_severity", ["severity"], unique=False)
        batch_op.create_index("ix_thrive_error_log_user_id", ["user_id"], unique=False)

    op.create_table(
        "thrive_llm_context",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("llm_provider", sa.String(length=50), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column("ddl_statements", sa.String(), nullable=True),
        sa.Column("documentation_snippets", sa.String(), nullable=True),
        sa.Column("question_sql_examples", sa.String(), nullable=True),
        sa.Column("ddl_count", sa.Integer(), nullable=True),
        sa.Column("doc_count", sa.Integer(), nullable=True),
        sa.Column("example_count", sa.Integer(), nullable=True),
        sa.Column("full_prompt", sa.String(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("retrieval_time_ms", sa.Integer(), nullable=True),
        sa.Column("inference_time_ms", sa.Integer(), nullable=True),
        sa.Column("total_time_ms", sa.Integer(), nullable=True),
        sa.Column("question", sa.String(length=1000), nullable=True),
        sa.Column("generated_sql", sa.String(), nullable=True),
        sa.Column("thinking_content", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["thrive_message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["thrive_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("thrive_llm_context", schema=None) as batch_op:
        batch_op.create_index("ix_thrive_llm_context_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_thrive_llm_context_llm_provider", ["llm_provider"], unique=False)
        batch_op.create_index("ix_thrive_llm_context_message_id", ["message_id"], unique=False)
        batch_op.create_index("ix_thrive_llm_context_user_id", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thrive_llm_context", schema=None) as batch_op:
        batch_op.drop_index("ix_thrive_llm_context_user_id")
        batch_op.drop_index("ix_thrive_llm_context_message_id")
        batch_op.drop_index("ix_thrive_llm_context_llm_provider")
        batch_op.drop_index("ix_thrive_llm_context_created_at")

    op.drop_table("thrive_llm_context")
    with op.batch_alter_table("thrive_error_log", schema=None) as batch_op:
        batch_op.drop_index("ix_thrive_error_log_user_id")
        batch_op.drop_index("ix_thrive_error_log_severity")
        batch_op.drop_index("ix_thrive_error_log_message_id")
        batch_op.drop_index("ix_thrive_error_log_created_at")
        batch_op.drop_index("ix_thrive_error_log_category")

    op.drop_table("thrive_error_log")
    with op.batch_alter_table("thrive_user_activity", schema=None) as batch_op:
        batch_op.drop_index("ix_thrive_user_activity_user_id")
        batch_op.drop_index("ix_thrive_user_activity_created_at")
        batch_op.drop_index("ix_thrive_user_activity_activity_type")

    op.drop_table("thrive_user_activity")
    with op.batch_alter_table("thrive_message", schema=None) as batch_op:
        batch_op.drop_index("ix_thrive_message_user_id")
        batch_op.drop_index("ix_thrive_message_type")
        batch_op.drop_index("ix_thrive_message_training_status")
        batch_op.drop_index("ix_thrive_message_feedback")
        batch_op.drop_index("ix_thrive_message_created_at")

    op.drop_table("thrive_message")
    with op.batch_alter_table("thrive_admin_action", schema=None) as batch_op:
        batch_op.drop_index("ix_thrive_admin_action_target_user_id")
        batch_op.drop_index("ix_thrive_admin_action_created_at")
        batch_op.drop_index("ix_thrive_admin_action_admin_id")
        batch_op.drop_index("ix_thrive_admin_action_action_type")

    op.drop_table("thrive_admin_action")
    op.drop_table("thrive_user")
    op.drop_table("thrive_user_role")
    # ### end Alembic commands ###
