"""add patient360 section cache

Revision ID: f55ddf6e521a
Revises: 768c88fc2924
Create Date: 2026-07-19 07:55:32.737465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55ddf6e521a'
down_revision: Union[str, Sequence[str], None] = '768c88fc2924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thrive_patient360_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=256), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('generator_version', sa.Integer(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thrive_patient360_section', schema=None) as batch_op:
        batch_op.create_index('ix_p360_source_section', ['source_id', 'section'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thrive_patient360_section', schema=None) as batch_op:
        batch_op.drop_index('ix_p360_source_section')

    op.drop_table('thrive_patient360_section')
    # ### end Alembic commands ###
