"""Write a pg_dump-compatible SQL dump (DDL + COPY blocks).

Postgres can load this via psql; SQLite loader translates COPY → INSERT.
"""

from __future__ import annotations

import datetime as dt
from typing import IO, Iterable


def _serialize(value) -> str:
    """Serialize a Python value for the COPY text format."""
    if value is None:
        return "\\N"
    if isinstance(value, bool):
        return "t" if value else "f"
    if isinstance(value, dt.datetime):
        return value.isoformat(sep=" ")
    if isinstance(value, dt.date):
        return value.isoformat()
    s = str(value)
    return s.replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n").replace("\r", "\\r")


def write_copy_block(
    out: IO[str],
    table: str,
    columns: list[str],
    rows: Iterable[dict],
) -> None:
    """Write one COPY block for `table`. `rows` is iterable of column dicts."""
    out.write(f"COPY {table} ({', '.join(columns)}) FROM stdin;\n")
    for row in rows:
        out.write("\t".join(_serialize(row.get(c)) for c in columns))
        out.write("\n")
    out.write("\\.\n\n")


def write_dump(
    out: IO[str],
    ddl: str,
    table_data: dict[str, tuple[list[str], list[dict]]],
) -> None:
    """Write DDL followed by COPY blocks. `table_data` keys are dotted names."""
    out.write("-- Generated by scripts/sample_db/etl.py — do not edit.\n")
    out.write("SET client_min_messages = warning;\n")
    out.write("SET statement_timeout = 0;\n\n")
    out.write(ddl.rstrip() + "\n\n")
    for table, (columns, rows) in table_data.items():
        write_copy_block(out, table, columns, rows)
