[ai_keys]
## Default Vanna functionality ##
# vanna_api = ""
# vanna_model = ""
## Open Router Values for Anthropic ##
# anthropic_api = ""
# anthropic_model = "claude-3-5-sonnet-latest"
## Local ollama install required ##
# ollama_model = "llama3.2"
## Google Gemini Configuration ##
# gemini_api = ""
# gemini_model = "gemini-2.0-flash-exp"

[rag_model]
### OPTIONAL ###
## ChromaDB Configuration for local RAG storage##
# chroma_path = "./chromadb"

[security]
allow_llm_to_see_data = 'False'

[cookie]
password = ""

[postgres]
host = "localhost"
port = 5469
database = "postgres"
user = "postgres"
password = "postgres"
## Database object type for training: "tables" or "views"
object_type = "tables"
## Database schema to query: default is "public"
schema_name = "public"
dialect = "redshift"

[sqlite]
database = "./pgDatabase/db.sqlite3"

[discord]
## Discord webhook URL for logging notifications (optional)
webhook_url = ""
